### ISSUE TITLE
Not converging in xor calculation task

### ISSUE THREAD

**Issue by saahiluppal** [kzl/universal-computation#2]
when i run ```demo.py``` notebook provided in this repository, calculating xor task converges.
but when i create and run a custom <a href='https://gist.github.com/saahiluppal/5c8c5198a481ab4f048b4dcb89a9999d'>notebook</a>, it doesnot converge and it is almost 2x slower

**Comment by kzl** [comment]
Sorry, I am not sure what the issue is, I would recommend using our notebook and codebase though.
